### ISSUE TITLE
Quick question about the code

### ISSUE THREAD

**Issue by catid** [RobertCsordas/moe_attention#2]
There's a lot of Python code in here so I have to ask:  Is this where the algorithm SwitchHead attention layer is implemented?

https://github.com/RobertCsordas/moe_attention/blob/master/layers/transformer/moa.py

Or is it in a different file?

**Comment by RobertCsordas** [comment]
Hi! No, it is here:

https://github.com/RobertCsordas/moe_attention/blob/master/layers/transformer/full_moe_relative_attention.py

I should provide a simple, easy-to-access implementation...

**Comment by RobertCsordas** [comment]
For a simple and easy-to-use code, please refer to https://github.com/robertcsordas/switchhead.
